###
# data sources
data_sources:
    casename: &casename
       g.e22.GOMIPECOIAF_JRA-1p4-2018.TL319_g17.4p2z.001
      #g.e22a06.G1850ECOIAF_JRA_PHYS_DEV.TL319_g17.scope_v1



# computation config keys
output_root: ./_computed-notebooks
default_kernel_name: cesm-exp
project: NCGD0011




###
# book table of contents
book_toc:
  format: jb-book
  root: description
  parts:
    - caption: Global overview
      chapters:
        - file: ocn-global-bgc-metrics
        
    - caption: Macronutrients
      chapters:
        - file: ocn-macronuts
        
    - caption: Ocean Carbon Cycle
      chapters:
        - file: ocn-carbonfluxes
        
    - caption: Phytoplankton
      chapters:
        - file: ocn-phyto-biomass
        - file: ocn-phyto-prod
        - file: ocn-phyto-lims
        - file: ocn-chl
        
    - caption: Zooplankton
      chapters:
        - file: ocn-zoo
        
    - caption: Dissolved iron
      chapters:
        - file: ocn-iron      
        
    - caption: Ocean Tracers
      chapters:
        - file: intro-ocn-tracer-views
          sections:
            - glob: ocn-tracer-views*
            
    - caption: Paper Figures
      chapters:
        - file: ocn-paperfigs

###
# book _config.yml keys
book_config_keys:
  title: My CESM Experiment
  repository:
    url: https://github.com/kristenkrumhardt/my-cesm-experiment
    path_to_book: notebooks
    branch: main

###
# computational notebooks
compute_notebooks:  

  description:
    use_cluster: False
    parameter_groups:
      none:
        casename: *casename
  
  ocn-carbonfluxes:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
        
  ocn-global-bgc-metrics:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
  
  ocn-tracer-views:
    use_cluster: True
    kernel_name: cesm-exp
    default_params:
      casename: *casename
      component: pop
      stream: h
    parameter_groups:
      temperature:
        variable_id: TEMP
      salinity:
        variable_id: SALT
      oxygen:
        variable_id: O2
      dissolved_inorganic_carbon:
        variable_id: DIC

  ocn-phyto-biomass:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
        
  ocn-phyto-prod:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
        
  ocn-chl:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
        
  ocn-phyto-lims:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
        
  ocn-zoo:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
        
  ocn-macronuts:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
        
  ocn-iron:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
  
  ocn-paperfigs:
    use_cluster: True
    parameter_groups:  
      none:
        casename: *casename
        component: pop
        stream: h
  